In [1]:
import hash_embedding
import hash_embedding_verbose
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
he = hash_embedding.HashEmbedding(num_words=5, 
    num_hash_buckets=7, 
    embedding_width=3, 
    num_hash_func=4, 
    append_weight=True, 
    aggregation_mode='append', 
    random_seed=1138)

In [4]:
he_verbose = hash_embedding_verbose.HashEmbedding(num_words=5, 
    num_hash_buckets=7, 
    embedding_width=3, 
    num_hash_func=4, 
    append_weight=True, 
    aggregation_mode='append', 
    random_seed=1138)

In [5]:
foo = he(tf.constant([[1,25,5384,900008],
                      [23490,2347,123,15],
                      [9234,234,1492,1224]],dtype=tf.int64))

In [6]:
foo

<tf.Tensor: shape=(3, 4, 16), dtype=float16, numpy=
array([[[ 2.4438e-06, -1.9073e-06, -8.9407e-07,  6.7949e-06,
         -3.9935e-06, -2.2054e-06,  7.1526e-07, -4.1723e-07,
         -2.3842e-07, -3.3259e-05,  7.5281e-05, -8.5175e-05,
          6.1512e-05, -1.0765e-04, -1.1027e-05,  4.1127e-04],
        [-1.8775e-05, -8.5533e-05, -2.5988e-05,  6.1989e-06,
         -4.8280e-06, -2.3246e-06, -1.2994e-05,  1.0192e-05,
          4.8280e-06,  8.0466e-06, -6.2585e-06, -2.9802e-06,
         -4.2152e-04,  1.5640e-04, -3.2735e-04,  2.0242e-04],
        [ 5.3644e-07, -2.2709e-05, -8.4043e-06,  6.7055e-05,
          3.5763e-07,  6.1989e-06, -1.6689e-06,  1.0133e-06,
          5.3644e-07, -3.5763e-07,  1.5616e-05,  5.7817e-06,
          3.9458e-04,  5.6505e-04,  2.6643e-05, -2.7180e-04],
        [-6.6757e-06,  1.9133e-05, -9.1076e-05, -2.0444e-05,
         -9.3162e-05, -2.8312e-05,  1.8358e-05, -4.1544e-05,
          4.6968e-05, -6.0201e-06,  1.7166e-05, -8.1718e-05,
         -5.5599e-04, -4.5919e

In [7]:
bar = he_verbose(tf.constant([[1,25,5384,900008],
                      [23490,2347,123,15],
                      [9234,234,1492,1224]],dtype=tf.int64))

hash table values
tf.Tensor([5 2 3 6 6], shape=(5,), dtype=int32)
tf.Tensor([5 1 2 5 2], shape=(5,), dtype=int32)
tf.Tensor([1 6 1 7 6], shape=(5,), dtype=int32)
tf.Tensor([3 1 3 5 4], shape=(5,), dtype=int32)

word importance
<tf.Variable 'hash_embedding_1/Variable:0' shape=(5, 4) dtype=float16, numpy=
array([[ 4.2033e-04, -1.8001e-04, -6.4373e-04,  7.8917e-04],
       [ 3.7599e-04, -1.1683e-04, -1.1873e-03,  8.6403e-04],
       [ 6.7949e-04,  5.9271e-04, -1.3947e-05,  1.0806e-04],
       [ 4.2653e-04,  2.7013e-04,  3.7599e-04, -3.2234e-04],
       [ 2.1040e-05,  2.4045e-04, -7.6675e-04,  1.8311e-04]],
      dtype=float16)>

embedding matrix
<tf.Variable 'hash_embedding_1/Variable:0' shape=(8, 3) dtype=float16, numpy=
array([[ 0.       ,  0.       ,  0.       ],
       [ 0.04443  ,  0.11316  ,  0.03638  ],
       [-0.05673  ,  0.186    ,  0.1504   ],
       [-0.0008335, -0.01823  , -0.0935   ],
       [ 0.152    ,  0.1016   , -0.0892   ],
       [ 0.00466  , -0.03247  , -0.04904  ],
 

In [8]:
bar

<tf.Tensor: shape=(3, 4, 16), dtype=float16, numpy=
array([[[-1.1921e-06,  3.9339e-06,  3.1590e-06,  1.0669e-05,
          2.7180e-05,  8.7619e-06,  9.3520e-05, -1.1623e-05,
         -1.0794e-04,  8.1062e-06,  2.0742e-05,  6.6757e-06,
          2.1040e-05,  2.4045e-04, -7.6675e-04,  1.8311e-04],
        [ 1.9670e-06, -1.3828e-05, -2.0921e-05,  1.2517e-06,
         -8.7619e-06, -1.3232e-05,  1.6689e-05,  4.2558e-05,
          1.3649e-05,  2.9802e-07,  5.9009e-06,  3.0160e-05,
          4.2653e-04,  2.7013e-04,  3.7599e-04, -3.2234e-04],
        [-8.2850e-05,  1.0312e-05,  9.5665e-05, -3.3617e-05,
          1.1027e-04,  8.9109e-05,  1.7285e-06, -2.3842e-07,
         -1.9670e-06,  1.6451e-05,  1.0967e-05, -9.6560e-06,
          6.7949e-04,  5.9271e-04, -1.3947e-05,  1.0806e-04],
        [-4.5836e-05,  5.6624e-06,  5.2929e-05, -5.3644e-07,
          3.8147e-06,  5.7220e-06,  3.8052e-04, -7.2181e-05,
          2.0862e-05,  4.0531e-06, -2.8074e-05, -4.2379e-05,
          3.7599e-04, -1.1683e