In [1]:
import hash_embedding
import hash_embedding_verbose
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
he = hash_embedding.HashEmbedding(num_words=5, 
    num_hash_buckets=7, 
    embedding_width=3, 
    num_hash_func=4, 
    append_weight=True, 
    aggregation_mode='append', 
    random_seed=1138)

In [3]:
he_verbose = hash_embedding_verbose.HashEmbedding(num_words=5, 
    num_hash_buckets=7, 
    embedding_width=3, 
    num_hash_func=4, 
    append_weight=True, 
    aggregation_mode='append', 
    random_seed=1138)

In [5]:
foo = he(tf.constant([[1,25,5384,900008],
                      [23490,2347,123,15],
                      [9234,234,1492,1224]],dtype=tf.int64))

In [6]:
foo

<tf.Tensor: shape=(3, 4, 16), dtype=float16, numpy=
array([[[ 7.1526e-07, -2.1458e-06,  1.0073e-05,  8.7023e-06,
         -1.9729e-05,  2.2292e-05, -4.7684e-07, -2.2650e-06,
         -6.5565e-07,  1.8358e-05,  8.3447e-05,  2.5332e-05,
          6.1512e-05, -1.0765e-04, -1.1027e-05,  4.1127e-04],
        [-5.0664e-06,  1.4544e-05, -6.9082e-05,  2.3842e-07,
         -9.0003e-06, -3.3379e-06, -0.0000e+00, -0.0000e+00,
         -0.0000e+00,  8.0466e-06, -6.2585e-06, -2.9802e-06,
         -4.2152e-04,  1.5640e-04, -3.2735e-04,  2.0242e-04],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -3.5822e-05,
          2.0862e-05,  1.1563e-05,  2.9802e-07, -8.9407e-07,
          4.3511e-06, -1.0788e-05,  8.4639e-06,  3.9935e-06,
          3.9458e-04,  5.6505e-04,  2.6643e-05, -2.7180e-04],
        [ 3.5226e-05, -2.0564e-05, -1.1384e-05, -1.8239e-05,
          1.4246e-05,  6.7353e-06, -0.0000e+00, -0.0000e+00,
         -0.0000e+00, -2.2233e-05, -1.0121e-04, -3.0756e-05,
         -5.5599e-04, -4.5919e

In [4]:
bar = he_verbose(tf.constant([[1,25,5384,900008],
                      [23490,2347,123,15],
                      [9234,234,1492,1224]],dtype=tf.int64))

hash table values
tf.Tensor([5 5 5 1 0], shape=(5,), dtype=int32)
tf.Tensor([4 3 6 2 1], shape=(5,), dtype=int32)
tf.Tensor([0 6 6 0 5], shape=(5,), dtype=int32)
tf.Tensor([2 6 2 6 2], shape=(5,), dtype=int32)

word importance
<tf.Variable 'hash_embedding/Variable:0' shape=(5, 4) dtype=float16, numpy=
array([[-1.4782e-04, -2.7966e-04,  5.0306e-04, -6.1035e-05],
       [-5.5599e-04, -4.5919e-04, -2.2697e-04, -4.9877e-04],
       [ 3.9458e-04,  5.6505e-04,  2.6643e-05, -2.7180e-04],
       [-4.2152e-04,  1.5640e-04, -3.2735e-04,  2.0242e-04],
       [ 6.1512e-05, -1.0765e-04, -1.1027e-05,  4.1127e-04]],
      dtype=float16)>

embedding matrix
<tf.Variable 'hash_embedding/Variable:0' shape=(8, 3) dtype=float16, numpy=
array([[ 0.       ,  0.       ,  0.       ],
       [-0.06335  ,  0.03696  ,  0.0205   ],
       [ 0.03976  , -0.03105  , -0.01471  ],
       [-0.0808   ,  0.1831   , -0.207    ],
       [ 0.001414 , -0.05756  , -0.02136  ],
       [ 0.01203  , -0.03445  ,  0.1638   ],
     

In [8]:
bar

<tf.Tensor: shape=(3, 4, 16), dtype=float16, numpy=
array([[[-1.1921e-06,  3.9339e-06,  3.1590e-06,  1.1325e-06,
         -7.8082e-06, -1.1802e-05,  4.3511e-05, -1.4269e-04,
         -1.1533e-04, -1.7881e-07, -3.3379e-06, -1.7107e-05,
          2.1040e-05,  2.4045e-04, -7.6675e-04,  1.8311e-04],
        [-2.4199e-05,  7.9334e-05,  6.4135e-05,  4.1068e-05,
          2.7478e-05, -2.4080e-05, -2.9802e-07, -6.8545e-06,
         -3.5167e-05, -1.4305e-05, -3.6478e-05, -1.1742e-05,
          4.2653e-04,  2.7013e-04,  3.7599e-04, -3.2234e-04],
        [ 1.0329e-04,  6.9082e-05, -6.0618e-05,  2.6345e-05,
          6.7055e-05,  2.1577e-05, -5.9605e-07, -1.5497e-06,
         -5.3644e-07,  1.6451e-05,  1.0967e-05, -9.6560e-06,
          6.7949e-04,  5.9271e-04, -1.3947e-05,  1.0806e-04],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -5.1856e-06,
         -1.3232e-05, -4.2319e-06,  1.0133e-06,  2.1636e-05,
          1.1104e-04, -7.1526e-07, -1.5736e-05, -8.0764e-05,
          3.7599e-04, -1.1683e